#!/bin/bash

#
# install without user input

DOTFILES_ROOT="`pwd`"
source "${DOTFILES_ROOT}/script/base/common.sh"
source "${DOTFILES_ROOT}/script/base/uninstall.sh"

set -e

echo ''
delete_all
echo ''
echo '  Cleaned!'
