#!/bin/bash

#
# install without user input

DOTFILES_ROOT="$(pwd)"
source "${DOTFILES_ROOT}/script/common.sh"

set -euo pipefail

install_antigen() {
  ANTIGEN_PATH="$HOME/src/zsh/antigen"
  if [[ -f "$ANTIGEN_PATH/antigen.zsh" ]]; then
    success "Antigen found at $ANTIGEN_PATH"
  else
    mkdir -p "$ANTIGEN_PATH"
    curl -L git.io/antigen > "$ANTIGEN_PATH/antigen.zsh"
    added "Antigen installed at $ANTIGEN_PATH"
  fi
}

install_homebrew() {
  if command -v brew > /dev/null 2>&1; then
    success "Homebrew found at $(which brew)"
  else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    added "Homebrew installed at $(which brew)"
  fi
}

install_mise() {
  if command -v mise > /dev/null 2>&1; then
    success "mise found at $(which mise)"
  else
    brew install mise
    added "mise installed at $(which mise)"
  fi
}

install_thefuck() {
  if command -v thefuck > /dev/null 2>&1; then
    success "thefuck found at $(which thefuck)"
  else
    brew install thefuck
    added "thefuck installed at $(which thefuck)"
  fi
}

install_starship() {
  if command -v starship > /dev/null 2>&1; then
    success "starship found at $(which starship)"
  else
    curl -sS https://starship.rs/install.sh | sh
    added "starship installed at $(which starship)"
  fi
}

download_fonts() {
  local FONT_DIR="$HOME/Library/Fonts"
  local FONT_NAME="Monaspice"
  local FONT_URL="https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Monaspace.zip"

  # Only do this for OSX
  if [[ -d "$FONT_DIR" ]]; then
    if ls "$FONT_DIR" | grep -q "$FONT_NAME"; then
      success "$FONT_NAME font found at $FONT_DIR"
    else
      curl -L "$FONT_URL" -o "$FONT_DIR/$FONT_NAME.zip"
      unzip -o "${FONT_DIR}/${FONT_NAME}.zip" -d "$FONT_DIR"
      rm "${FONT_DIR}/${FONT_NAME}.zip" "${FONT_DIR}/LICENSE" "${FONT_DIR}/README.md"
      added "$FONT_NAME font downloaded to $FONT_DIR"
    fi
  fi
}

echo
echo "Setup dependencies..."
install_antigen
install_homebrew
install_mise
install_thefuck
install_starship
download_fonts

echo
echo "Setup dotfiles..."
install_dotfiles "$DOTFILES_ROOT"
