#!/bin/bash

#
# install without user input

DOTFILES_ROOT="`pwd`"
source "${DOTFILES_ROOT}/script/base/common.sh"
source "${DOTFILES_ROOT}/script/base/uninstall.sh"

set -e

install_antigen() {
  # Install the antigen plugin/theme manager if it's not already installed.
  if [[ ! -d $HOME/antigen ]]; then
    echo -e "Antigen not found, installing..."
    mkdir -p $HOME/src/zsh
    cd $HOME/src/zsh
    git clone https://github.com/zsh-users/antigen.git
    cd -
  fi
}

install_dotfiles() {
  info 'installing dotfiles'
  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"
    link_file $source $dest
  done
}

echo ''
delete_all
install_antigen
install_dotfiles
echo ''
echo '  Installed!'
